version: '3.2'

services:

  jenkins-docker:
    container_name: jenkins-docker-submission
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases:
          - "docker"

    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./jenkins-docker-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
      - 3000:3000
    command: --storage-driver=overlay2

  jenkins-blueocean:
    container_name: jenkins-blueocean-submission
    image: ofid/myjenkins-blueocean:2.346.1-1
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
    ports:
      - 49000:8080
      - 50000:50000
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client:ro
      - ${HOME}:/home
    restart: on-failure

  nginx:
    image: nginx:stable-alpine
    ports:
      - 9000:9000
    networks:
      - jenkins
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./jenkins-data/:/jenkins-data/
      - ./nginx/logs/:/var/log/nginx/
    restart: on-failure

networks:
  jenkins: